### ISSUE TITLE
Blog card directs to 404, blog direct path working

### ISSUE THREAD

**Issue by ksatx** [stoplightio/stoplight.io#1327]
**Describe the bug**
When you go to [https://stoplight.io/blog/page/7/](https://stoplight.io/blog/page/7/) and click on “The Evolution of a JavaScript Function”, it gives you a 404, but if you go straight to the URL it's fine [https://stoplight.io/blog/the-evolution-of-a-javascript-function-994ebd95d941/](https://stoplight.io/blog/the-evolution-of-a-javascript-function-994ebd95d941/)

Refreshing the 404 page takes you to the blog. 

"Uncaught Error: URL contains XSS injection attempt"

**Screenshots**

![2020-01-28 11 15 45](https://user-images.githubusercontent.com/51092436/73286118-ac624580-41bc-11ea-9752-31f22deb6175.gif)

**Comment by wmhilton** [comment]
_enter: detective_

Are we using Contentful? Googling the error took me to this: https://github.com/axios/axios/issues/2522#issuecomment-575053385

which took me to this: https://github.com/axios/axios/issues/2522

which makes me think it might be something as simple and stupid as "it don't work because the URL contains the word `javascript`" which _sounds_ really stupid BUT it _is_ the only blog post containing the work "javascript" in its filename in this directory (https://github.com/stoplightio/stoplight.io/tree/master/netlify/blog-posts) sooooooooo I've seen webpages break for dumber reasons. 🤷‍♂

**Comment by ksatx** [comment]
No, we're not using [Contentful](https://www.contentful.com/), at least to my knowledge, but we are using [Convertful](https://convertful.com/). I don't think they're related.

**Comment by ksatx** [comment]
The specific occurrence was resolved with https://github.com/stoplightio/stoplight.io/pull/1328 and Will has an approved PR to fix future occurrences https://github.com/stoplightio/platform-internal/issues/772
