### ISSUE TITLE
Linkedin/Facebook can't scrape blog metadata

### ISSUE THREAD

**Issue by ksatx** [stoplightio/stoplight.io#1330]
LinkedIn uses [Open Graph tags](https://ogp.me/) to retrieve metadata on blogs posts and create a preview. Currently, all Stoplight blog posts generate previews with the default site metadata.  

Previews can be edited from a business account (like Stoplight's page) but can't be edited from a personal share, like an employee amplifying content. 

Facebook has the same problem, unsure if they also use Open Graph tags. 

Twitter doesn't have the same problem. Blog markdown files contain a specific twitter meta section.

`meta:
  description: >-
    In this post, we’ll look at the benefits of a forward-thinking API approach and how it is impacted across the full lifecycle.
  favicon: /images/mark_light_bg.png
  robots: 'index, follow'
  title: >-
    API Development Demystified
  image: /images/sasha-stories-unsplash-resized.png
  twitter:
    title: >-
      Stoplight Blog: API Development Demystified
    image: /images/sasha-stories-unsplash-resized.png
    username: '@stoplightio'
`

To reproduce, grab the URL of a blog post, like [https://stoplight.io/blog/api-development-demystified/](https://stoplight.io/blog/api-development-demystified/). Create a new LinkedIn post, paste in the URL, and wait for the preview to load. 

![image](https://user-images.githubusercontent.com/51092436/73312595-b2711a00-41ee-11ea-9073-664cb00a5230.png)

**Comment by ksatx** [comment]
Opened https://github.com/stoplightio/stoplight.io/pull/1333 to experiment with Og meta fields

**Comment by paulatulis** [comment]
@ksatx the changes implemented in https://github.com/stoplightio/stoplight.io/pull/1333 don't affect the metatags in LinkedIn in [production](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fstoplight.io%2Fblog%2Fapi-development-demystified%2F) - only with the [Netlify preview](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fdeploy-preview-1333--stoplightio.netlify.com%2Fblog%2Fapi-development-demystified%2F). 

I'm curious if this is because it takes a couple of days for the new tags to be indexed by Google or if it's something else. 

Maybe we can check again on this in a few days and see if there's any change.

**Comment by ksatx** [comment]
Sounds good!

**Comment by ksatx** [comment]
@paulatulis I just remembered that Sarah did this stuff a while back, not sure if it has any baring on the current issue https://github.com/stoplightio/stoplight.io/pull/1126

**Comment by paulatulis** [comment]
Thank you! It looks like this is kind of the same thing we are doing now...I don't see a specific resolution to the issue, but will ask Sarah if she remembers working on it.

**Comment by paulatulis** [comment]
@lottamus I've been trying to trace this back to the root of where it's happening, but there are some gaps I don't quite understand. 

For context: we would like the blog-specific meta tags to pull in when posting a Stoplight blog on LinkedIn. It should look like [this (netlify preview link works)](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fdeploy-preview-1333--stoplightio.netlify.com%2Fblog%2Fapi-development-demystified%2F), but it looks like [this (actual production link)](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fstoplight.io%2Fblog%2Fapi-development-demystified%2F).


In the [MetaTags config file,](https://github.com/stoplightio/stoplight.io/blob/master/src/components/MetaTags/config.js#L6) it says that meta tags will default to the meta tags in [settings](https://github.com/stoplightio/stoplight.io/blob/master/netlify/settings.yaml#L157). 

I believe that this happens because the subpage template is being exported [withRouteData](https://github.com/stoplightio/stoplight.io/blob/master/src/templates/Subpage/index.tsx#L145), so it's taking the tags from settings.yaml. My understanding is that we do want to export the template with route data, just not the default meta tags because we have meta tags that are unique to the blog post specified in the [subpage's markdown file](https://github.com/stoplightio/stoplight.io/blame/master/netlify/blog-posts/api-development-demystified.md#L20).

Does this have something to do with [this line in the Header component ](https://github.com/stoplightio/stoplight.io/blob/master/src/components/Header/index.tsx#L114)? Or would it be good to look more at the [createListRoutes](https://github.com/stoplightio/stoplight.io/blob/master/src/utils/getRoutes.js#L208) and/or [blogPostProps](https://github.com/stoplightio/stoplight.io/blob/master/src/utils/getRoutes.js#L309) functions? 

I also was trying to see if this is something I need to change on the [document.js file](https://github.com/stoplightio/stoplight.io/blob/master/src/utils/document.js#L5), but nothing I tried was doing much of anything.

When I console.log the metadata, I get the correct tags...
<img width="1417" alt="Screenshot 2020-02-03 at 1 00 05 PM" src="https://user-images.githubusercontent.com/47359669/73682248-9e616880-4685-11ea-8c34-054fa3f33e0e.png">

...but it's not showing up in the <head> section
<img width="781" alt="Screenshot 2020-02-03 at 1 01 49 PM" src="https://user-images.githubusercontent.com/47359669/73682262-aa4d2a80-4685-11ea-8b7e-15b51bb3002d.png">

Let me know if you have any ideas or suggestions. I appreciate it!

**Comment by lottamus** [comment]
@paulatulis I suggest using Facebook's opengraph debugger tool instead. It should give you a better idea of where the information is actually coming from: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fstoplight.io%2Fblog%2Fapi-development-demystified%2F

It looks like the "org:url" meta tag is pointing at stoplight.io, thus opengraph is pulling the metatags from stoplight.io instead of the current webpage

<img width="1511" alt="Screen Shot 2020-02-04 at 1 03 19 AM" src="https://user-images.githubusercontent.com/7423098/73721592-3a24c000-46ea-11ea-8847-ca1ad8395426.png">

That url is being set by the "meta.url" property here: https://github.com/stoplightio/stoplight.io/blob/master/src/utils/document.js#L54

I suggest moving the "og" properties to the root "meta" object rather than inside "og" isn't being used anywhere: https://github.com/stoplightio/stoplight.io/blame/ae6c5cff04139044b4bdb44298803b001e70f3cb/netlify/blog-posts/api-development-demystified.md#L33-L38

**Comment by paulatulis** [comment]
@lottamus Thank you so much for the tips! Will proceed with all of this in mind.
